{{- if not .Values.ingress_disabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "connection-manager.fullname" . }}-ingress
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api/
            backend:
              serviceName: {{ include "connection-manager.fullname" . }}-api
              servicePort: {{ .Values.api.ports.containerPort }}
          - path: /
            backend:
              serviceName: {{ include "connection-manager.fullname" . }}-ui
              servicePort: {{ .Values.ui.ports.containerPort }}
{{- end -}}
