{{- if not .Values.ui.disabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connection-manager.fullname" . }}-ui
  labels:
    app.kubernetes.io/component: ui
{{ include "connection-manager.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "connection-manager.fullname" .}}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: connection-manager-ui
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.api.url | quote }}
            - name: AUTH_ENABLED
              value: {{ .Values.api.oauth.enabled | quote }}
          {{- with .Values.ui }}
          image: "{{ .image.name }}:{{ .image.version }}"
          ports:
            - containerPort: {{ .ports.containerPort }}
          {{- end }}
          resources: {}
          stdin: true
          tty: true
      hostname: connection-manager-ui
      restartPolicy: Always
status: {}
{{- end -}}
